version: 2

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - weiyunlu
  assignees:
  - weiyunlu
  ignore:
  - dependency-name: aws-sdk-s3
    versions:
    - 1.88.1
    - 1.88.2
    - 1.89.0
    - 1.90.0
    - 1.92.0
    - 1.93.1
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
  - dependency-name: codecov
    versions:
    - 0.5.0
  - dependency-name: rubocop-performance
    versions:
    - 1.10.0
  - dependency-name: timecop
    versions:
    - 0.9.2
    - 0.9.3
  - dependency-name: aws-sdk-kms
    versions:
    - 1.42.0
  - dependency-name: rubocop-rspec
    versions:
    - 1.44.1
  - dependency-name: msgpack
    versions:
    - 1.4.1
