require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - db/**/*.rb
    - node_modules/**/*
    - output/**/*
    - vendor/**/*
  TargetRubyVersion: 2.5.3
  RSpec:
    Patterns:
      - _spec.rb
      - "(?:^|/)spec/"
    SpecTypes:
      Feature: 'spec/features/**/*'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 160

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Style/StringLiterals:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10
